name: ${ENV:-dev}
services:
  db:
    image: postgres:17
    environment:
    - POSTGRES_PASSWORD=s3cr3t
    labels:
    - traefik.enable=false
    volumes:
    - vipdb:/var/lib/postgresql/data
    - ./sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 1s
      retries: 3

  web:
    image: nginx:1.27-alpine
    ports:
      - 80
    networks:
      - infra
      - default
    volumes:
      - www:/usr/share/nginx/html

  generator:
    build:
      context: https://github.com/lalyos/docker-nova.git
      dockerfile_inline: |
        FROM postgres:17
        COPY start-generator.sh /start.sh
        RUN chmod +x /start.sh
        CMD ["/start.sh"]
    image: generator
    environment:
      - COLOR=${COLOR:-orange}
      - ENV=${ENV:-dev}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - www:/www
    init: true
    stop_grace_period: "0"
    ports:
    - 80
  adminer:
    image: adminer
    ports:
      - 8080
    labels:
      - traefik.frontend.auth.basic=admin:$$1$$I5Kt8BwT$$G4y6mBV3xVzyZKUECxqV61
    networks:
      - infra
      - default

volumes:
  vipdb:
  www:

networks:
  default:
  infra:
    external: true