name: dev
services:
  db:
    image: postgres:17
    environment:
    - POSTGRES_PASSWORD=s3cr3t
    volumes:
    - vipdb:/var/lib/postgresql/data
    - ./sql:/docker-entrypoint-initdb.d
  
  vip:
    build:
      # context: .
      dockerfile: Dockerfile.vip
      context: https://github.com/lalyos/docker-nova.git
    image: vip
    init: true
    ports:
    - 80
  adminer:
    image: adminer
    ports:
      - 8080

volumes:
  vipdb: