name: dev
services:
  db:
    image: postgres:17
    environment:
    - POSTGRES_PASSWORD=s3cr3t
    volumes:
    - vipdb:/var/lib/postgresql/data
    - ./sql:/docker-entrypoint-initdb.d

  web:
    image: nginx:1.27-alpine
    ports:
      - 80
    volumes:
      - www:/usr/share/nginx/html

  generator:
    build:
      dockerfile_inline: |
        FROM postgres:17
        COPY start-generator.sh /start.sh
        RUN chmod +x /start.sh
        CMD ["/start.sh"]
    image: generator
    volumes:
      - www:/www
    init: true
    ports:
    - 80
  adminer:
    image: adminer
    ports:
      - 8080

volumes:
  vipdb:
  www: